# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
